import './globals.css'
import { Inter } from 'next/font/google'
import ComplexNavbar from './navbar'
import 'react-toastify/dist/ReactToastify.css';

import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className='w-full py-2 my-4'>
          <ComplexNavbar />
        </div>
        <ToastContainer />
        {children}
      </body>
    </html>
  )
}
